### ISSUE TITLE
Lachryvisions conflicts with BugTorch or LegacyFixes

### ISSUE THREAD

**Issue by Omgise** [Lachrymogenic/Lachryvisions#3]
Lachryvisions will destroy the function that keeps the farmland from being trampled, can you fix it, thank you!
LegacyFixes：https://github.com/unilock/LegacyFixes
BugTorch：https://github.com/jss2a98aj/BugTorch

**Comment by Lachrymogenic** [comment]
I have fixed it. The function wasn't getting destroyed, what happened was that LegacyFixes' function comes after my function and my function rewrites the original and cancels out the original. The easiest way to fix this is by adding a Config check, so, if you have Lachryvisions' "Leather Boots Protect Crops" set to False, but LegacyFixes "NoTrample" set to true, then crops will not be trampled. But, if you set Lachryvisions' "Leather Boots Protect Crops" to true and NoTrample to true, then the game will check for a legacyfixes config file and if NoTrample is true then crops will not be trampled.

So essentially, LegacyFixes "noTrample" now cancels out "LeatherBootsProtectCrops"

What's the issue with BugTorch specifically?

**Comment by Omgise** [comment]
There's no problem with BugTorch either, because BugTorch also has a farmland stomp-free feature, similar to LegacyFixes

**Comment by Lachrymogenic** [comment]
It seems like my mod overwrites both of those mods. So if you have Lachryvisions and BugTorch then crop trampling will still occur. I don't know how to detect BugTorch but I can add a line of code that possibly detects BugTorch and if BugTorch is installed, then crops wont be trampled, however I do have a different idea

Would it just be better to create a configurable enum called "Crop Trampling" that you can switch to "No Crop Trampling, Crops Trample and Crops Protected by Leather Boots" ?

**Comment by Omgise** [comment]
Yes

**Comment by Lachrymogenic** [comment]
Crop trampling is now decided by an enum in the mod's config.
The button cycles through 3 options, Crop Trampling on, Crops protected by boots and Crop trampling off.
![image](https://github.com/Lachrymogenic/Lachryvisions/assets/160751404/92d7d2a0-03fb-49ce-9d40-49aef7a5eea9)
![image](https://github.com/Lachrymogenic/Lachryvisions/assets/160751404/a7db72a9-61a2-430a-a2dd-a5ecd2a0fc4e)

**Comment by Omgise** [comment]
perfect！
